package main

import (
	"os"
	"log"
	"encoding/csv"
)

var data = [][]string{
	{"nodeid","nodeaddress","nodedistance","nodebucket"}, /* should always be in the file*/
	{"1","mapAddress","5","6"}, /* Lines should be autogenerated and filled */
}

func main() {
	file, err := os.Create( "temp.csv") /* Filename should be set to the sought after node, need to create this function*/
	checkError2("Cannot create file", err)
	defer file.Close()

	writer := csv.NewWriter(file)
	defer writer.Flush()

	for _, value := range data {
		err := writer.Write(value)
		checkError2("Cannot write to file", err)
	}
}

func checkError2(message string, err error) {
	if err != nil {
		log.Fatal(message, err)
	}
}
