// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ProtoTest.proto

/*
Package ProtobufTest is a generated protocol buffer package.

It is generated from these files:
	ProtoTest.proto

It has these top-level messages:
	TestMessage
*/
package ProtobufTest

import proto "protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TestMessage struct {
	Messageitems     []*TestMessage_MsgItem `protobuf:"bytes,1,rep,name=messageitems" json:"messageitems,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *TestMessage) Reset()                    { *m = TestMessage{} }
func (m *TestMessage) String() string            { return proto.CompactTextString(m) }
func (*TestMessage) ProtoMessage()               {}
func (*TestMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TestMessage) GetMessageitems() []*TestMessage_MsgItem {
	if m != nil {
		return m.Messageitems
	}
	return nil
}

type TestMessage_MsgItem struct {
	NodeId           *int32  `protobuf:"varint,1,req,name=nodeId" json:"nodeId,omitempty"`
	NodeAddress      *string `protobuf:"bytes,2,opt,name=nodeAddress" json:"nodeAddress,omitempty"`
	NodeDistance     *int32  `protobuf:"varint,3,opt,name=nodeDistance" json:"nodeDistance,omitempty"`
	NodeBucket       *int32  `protobuf:"varint,4,opt,name=nodeBucket" json:"nodeBucket,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TestMessage_MsgItem) Reset()                    { *m = TestMessage_MsgItem{} }
func (m *TestMessage_MsgItem) String() string            { return proto.CompactTextString(m) }
func (*TestMessage_MsgItem) ProtoMessage()               {}
func (*TestMessage_MsgItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *TestMessage_MsgItem) GetNodeId() int32 {
	if m != nil && m.NodeId != nil {
		return *m.NodeId
	}
	return 0
}

func (m *TestMessage_MsgItem) GetNodeAddress() string {
	if m != nil && m.NodeAddress != nil {
		return *m.NodeAddress
	}
	return ""
}

func (m *TestMessage_MsgItem) GetNodeDistance() int32 {
	if m != nil && m.NodeDistance != nil {
		return *m.NodeDistance
	}
	return 0
}

func (m *TestMessage_MsgItem) GetNodeBucket() int32 {
	if m != nil && m.NodeBucket != nil {
		return *m.NodeBucket
	}
	return 0
}

func init() {
	proto.RegisterType((*TestMessage)(nil), "ProtobufTest.TestMessage")
	proto.RegisterType((*TestMessage_MsgItem)(nil), "ProtobufTest.TestMessage.MsgItem")
}

func init() { proto.RegisterFile("ProtoTest.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x0f, 0x28, 0xca, 0x2f,
	0xc9, 0x0f, 0x49, 0x2d, 0x2e, 0xd1, 0x2b, 0x00, 0xb1, 0x84, 0x78, 0xc0, 0x02, 0x49, 0xa5, 0x69,
	0x20, 0x31, 0xa5, 0x7b, 0x8c, 0x5c, 0xdc, 0x20, 0x86, 0x6f, 0x6a, 0x71, 0x71, 0x62, 0x7a, 0xaa,
	0x90, 0x2b, 0x17, 0x4f, 0x2e, 0x84, 0x99, 0x59, 0x92, 0x9a, 0x5b, 0x2c, 0xc1, 0xa8, 0xc0, 0xac,
	0xc1, 0x6d, 0xa4, 0xa8, 0x87, 0xac, 0x49, 0x0f, 0x49, 0x83, 0x9e, 0x6f, 0x71, 0xba, 0x67, 0x49,
	0x6a, 0x6e, 0x10, 0x8a, 0x36, 0xa9, 0x76, 0x46, 0x2e, 0x76, 0xa8, 0x8c, 0x90, 0x18, 0x17, 0x5b,
	0x5e, 0x7e, 0x4a, 0xaa, 0x67, 0x8a, 0x04, 0xa3, 0x02, 0x93, 0x06, 0x6b, 0x10, 0x94, 0x27, 0xa4,
	0xc0, 0xc5, 0x0d, 0x62, 0x39, 0xa6, 0xa4, 0x14, 0xa5, 0x16, 0x17, 0x4b, 0x30, 0x29, 0x30, 0x6a,
	0x70, 0x06, 0x21, 0x0b, 0x09, 0x29, 0x71, 0xf1, 0x80, 0xb8, 0x2e, 0x99, 0xc5, 0x25, 0x89, 0x79,
	0xc9, 0xa9, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x28, 0x62, 0x42, 0x72, 0x5c, 0x5c, 0x20,
	0xbe, 0x53, 0x69, 0x72, 0x76, 0x6a, 0x89, 0x04, 0x0b, 0x58, 0x05, 0x92, 0x08, 0x20, 0x00, 0x00,
	0xff, 0xff, 0xca, 0xf1, 0x47, 0x1e, 0x00, 0x01, 0x00, 0x00,
}
